
name: "conda channel fetcher"

on:
  push:
    branches: [ "ci*" ]
  schedule:
    - cron:  "13 6,18 * * *"
  workflow_dispatch:

jobs:

  update-conda:
    name: Update conda channels
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install/Setup - NIX
      uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: update
      run: |
        set -x
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        nix run -L .#job-conda
        git push

      shell: bash
